### ISSUE TITLE
convrnx转换rtcm3到rinex3.04数据缺少频点

### ISSUE THREAD

**Issue by fuyongjia** [IPNL-POLYU/pyrtklib_demo5#1]
您好，用demo5 b34j编译好的rtkconv把rtcm3转换为rinex3.04，GPS和北斗频点是完整的
![image](https://github.com/user-attachments/assets/e2caad12-ec4e-47af-872c-331b201dcab7)
但是python调用convrnx转换后GPS和北斗缺少频点
![image](https://github.com/user-attachments/assets/44d9c866-b5a7-418a-93a2-bd142e2cfdcd)

请忽略GLO，麻烦有时间您给指导一下，谢谢

**Comment by ebhrz** [comment]
您好，pyrtklib_demo5中使用的版本是demo5 b34h，您可以尝试替换rtksrc下的源码重新编译，二进制更新可能会在下一个版本中放出

**Comment by fuyongjia** [comment]
> 您好，pyrtklib_demo5中使用的版本是demo5 b34h，您可以尝试替换rtksrc下的源码重新编译，二进制更新可能会在下一个版本中放出

尝试了一下pyrtklib5.cpp会报很多“未声明的标识符”错误，我一边学习一边等您的更新吧，谢谢！
